"""initial database migration

Revision ID: ff6765e7ad35
Revises: 
Create Date: 2020-07-10 23:05:59.653393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6765e7ad35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('language',
    sa.Column('language_id', sa.String(length=5), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    sa.UniqueConstraint('language_id'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('company_info',
    sa.Column('company_id', sa.String(length=255), nullable=False),
    sa.Column('language_id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.language_id'], ),
    sa.PrimaryKeyConstraint('company_id', 'language_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_info')
    op.drop_table('language')
    op.drop_table('company')
    # ### end Alembic commands ###
