FROM ubuntu:latest

MAINTANER Heizel Kim <hrkim0624@gmail.com>

RUN apt-get clean && \
    apt-get update && \
    apt-get install python3-pip  \
        pkg-config \
        curl \
        wget \
    apt-get clean && apt-get autoremove -y && \
    rm -rf /var/cache/apk/*

COPY ./requirements.txt SearchCompany/app/requirements.txt

VOLUME ["SearchCompany"]
WORKDIR SearchCompany

RUN pip install -r requirements.txt

COPY . SearchCompany

ENTRYPOINT [ "python" ]

CMD [ "manage.py run" ]

# Set python as python3
RUN echo alias python=/usr/bin/python3 >> /root/.bashrc

# Fix locale as US.UTF-8.
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8


# DOCKERFILE for Peer.

