FROM ubuntu:latest

LABEL maintainer="Heizel Kim <hrkim0624@gmail.com>"

RUN apt-get update && apt-get install -y \
    python3-pip \
    curl \
 && rm -rf /var/lib/apt/lists/*

WORKDIR SearchCompany

RUN mkdir ./app/

COPY ./app/ ./app/
COPY ./manage.py manage.py
COPY ./requirements.txt requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5000

RUN chmod u+x manage.py

ENTRYPOINT [ "python3" ]

CMD [ "manage.py", "run" ]

RUN echo alias python=/usr/bin/python3 >> /root/.bashrc

